# Generated by Django 2.2.11 on 2021-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0011_wishlistdpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Фото'),
        ),
    ]
