# Generated by Django 2.2.11 on 2021-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0012_wishlistmodel_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistdpmodel',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Фото'),
        ),
    ]
