# Generated by Django 2.2.11 on 2021-07-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200410_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
